### ISSUE TITLE
Unknown License

### ISSUE THREAD

**Issue by ilyar** [phaldan/asset-builder#1]

**Comment by phaldan** [comment]
I have added the MIT license. Is that ok for you @ilyar?
But you should consider not to use my project, because it was only a proof of concept for my bachelor thesis.

**Comment by ilyar** [comment]
> Unknown License
in https://packagist.org/packages/phaldan/asset-builder 
for fix need edit `composer.json`

**Comment by ilyar** [comment]
> But you should consider not to use my project, because it was only a proof of concept for my bachelor thesis.

Are there any other reasons not to use and develop your project? I liked your project.

**Comment by phaldan** [comment]
@ilyar I have pushed a new version to packagist and also added a readme with a short usage example.

Also I personally doesn't use this library anymore, because I switched to NodeJS for asset bundling, minification or LESS to CSS transformation. Webpack for example is very flexible and resolves your dependencies like jQuery directly via NPM, but the initial configuration takes much more time and you need NodeJS beside your PHP installation.

**Comment by ilyar** [comment]
I also use it (NodeJS, etc), but it is not always possible
